### ISSUE TITLE
Save position from the main window does not work

### ISSUE THREAD

**Issue by Oxyd** [Oxyd/APNS#1]
1) Load a position
2) Run search
3) Click a vertex in the tree
4) Click Save Position
5) Observe that it hasn't been saved

**Comment by Oxyd** [comment]
Looks like a bug in gui.pyw.

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/lib-tk/Tkinter.py", line 1410, in **call**
    return self.func(_args)
  File "/usr/home/oxyd/BACKUP/development/skola/rocnikac/APNS/APNS/interface/gui.py", line 65, in <lambda>
    command=lambda: self.notifyObservers(command=MainWindow.Command.save))
  File "/usr/home/oxyd/BACKUP/development/skola/rocnikac/APNS/APNS/interface/observable.py", line 17, in notifyObservers
    observer.update(self, *_kwargs)
  File "/usr/home/oxyd/BACKUP/development/skola/rocnikac/APNS/APNS/interface/gui.py", line 170, in update
    self._resultsCtrl.save(str(filename))
  File "/usr/home/oxyd/BACKUP/development/skola/rocnikac/APNS/APNS/interface/gui.py", line 455, in save
    if self._resultsDsply.getNodeType(selectedHandle) == 'AND':
  File "/usr/home/oxyd/BACKUP/development/skola/rocnikac/APNS/APNS/interface/gui.py", line 319, in getNodeType
    return self._tree.set(node, 'Type')
  File "/usr/local/lib/python2.7/lib-tk/ttk.py", line 1447, in set
    res = self.tk.call(self._w, "set", item, column, value)
TclError: Invalid column index Type
